export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

// user
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'

