export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

// user
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'

// promise
export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_PENDING = 'LOAD_USER_PENDING'
export const LOAD_USER_FULFILLED = 'LOAD_USER_FULFILLED'
export const LOAD_USER_REJECTED = 'LOAD_USER_REJECTED'
